version: '3.2'

# Criando Redes
networks:
  net-local:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.38.1.0/24

services:

#- Serviço Banco de Dados
    mysql:
      build:
        context: .
        dockerfile: ./Dockerfile/Dockerfile-mysql
      container_name: mysql
      env_file:
        - .env
      environment:
        - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
        - MYSQL_PASSWORD=${PASSWORD}
        - MYSQL_DATABASE=${DATABASE}
        - MYSQL_USER=${USER}
      ports:
        - "3306:3306"
      volumes:
        - "./infra/mysql/db:/var/lib/mysql"
      networks:
        net-local:
          ipv4_address: 172.38.1.2
      extra_hosts:
          - "laravel.local:172.38.1.5"

#- Serviço Gerenciamento Banco de Dados PHP-MYADMIN
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      links:
         - mysql:mysql
      environment:
        - PMA_ARBITRARY=1
      restart: always
      ports:
       - "8080:80"
      networks:
        net-local:
          ipv4_address: 172.38.1.3
      extra_hosts:
          - "laravel.local:172.38.1.5"

#- Console de Comandos "artisan", "composer", "curl", "gulp", "bower" inclui serviço nodejs portas não configuradas.
    comandos:
      build:
        context: .
        dockerfile: Dockerfile/Dockerfile-comandos
      container_name: comandos
      volumes:
       - "./dev:/var/www/html"
      restart: always
      networks:
        net-local:
          ipv4_address: 172.38.1.4
      extra_hosts:
          - "laravel.local:172.38.1.5"
#- Serviço Web Server (Nginx)
    web:
      image: nginx:latest
      container_name: web
      links:
        - mysql:mysql
        - redis:redis
        - php:php
        - elasticsearch:elasticsearch
        - memcache:memcache
        - rabbitmq:rabbitmq
        - mongodb:mongodb
      restart: always
      ports:
       - "80:80"
      volumes:
       - "./dev:/var/www"
       - "./infra/nginx/conf.d:/etc/nginx/conf.d"
      networks:
        net-local:
          ipv4_address: 172.38.1.5
      extra_hosts:
          - "laravel.local:172.38.1.5"

#- Serviço de PHP-FPM 7
    php:
      build:
        context: .
        dockerfile: Dockerfile/Dockerfile-phpfpm
      container_name: php
      environment:
        XDEBUG_CONFIG: "remote_host=localhost"
        PHP_IDE_CONFIG: "serverName=web"
      volumes:
       - "./dev:/var/www"
       - "./infra/php/php.ini:/usr/local/etc/php/php.ini"
      ports:
       - "9000:9000"
      networks:
        net-local:
          ipv4_address: 172.38.1.6
      extra_hosts:
          - "laravel.local:172.38.1.5"

#- Serviço de Cache de Memória
    redis:
      container_name: redis
      image: redis:alpine
      restart: always
      ports:
       - "6379:6379"

#- MongoDB: https://hub.docker.com/_/mongo/
    mongodb:
      build:
        context: .
        dockerfile: Dockerfile/Dockerfile-mongodb
      container_name: mongodb
      volumes:
       - "./infra/mongodb/data:/var/lib/mongodb"
       - "./infra/mongodb/config/mongodb.conf:/etc/mongodb.conf"
      restart: always
      extra_hosts:
          - "laravel.local:172.38.1.5"
      ports:
       - "27017:27017"

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
      container_name: elasticsearch
      environment:
        - http.host=0.0.0.0
      # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
        - xpack.security.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      extra_hosts:
          - "laravel.local:172.38.1.5"
      ports:
       - "9200:9200"
       - "9300:9300"

    memcache:
      build:
        context: .
        dockerfile: Dockerfile/Dockerfile-memcached
      volumes:
       - "./infra/memcached/memcached.conf:/etc/memcached.conf"
      restart: always
      ports:
       - "11211:11211"

    rabbitmq:
      build:
        context: .
        dockerfile: Dockerfile/Dockerfile-rabbitmq
      container_name: rabbitmq
      restart: always
      extra_hosts:
          - "laravel.local:172.38.1.5"
      ports:
       - "4369:4369"
       - "5671:5671"
       - "5672:5672"
       - "15671:15671"
       - "15672:15672"

